server:
    port: 8087
    error:
        include-stacktrace: never
    servlet:
        context-path: '/ead-authuser/'

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ead_authuser?useSSL=false&serverTimezone=UTC
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                '[use_new_id_generator_mappings]': true
                dialect: org.hibernate.dialect.MySQL8Dialect
                '[format_sql]': true
                jdbc:
                    lob:
                        non-contextual-creation: true
                id:
                    generator:
                        uuid:
                            style: random
    output:
        ansi:
            enabled: always # Enable ANSI colors in the console output(padrão de cores para o Windows)

logging:
    level:
        '[com.ead]': TRACE
        root: INFO
        '[org.springframework]': DEBUG
        '[org.hibernate]': INFO
