server:
    port: 8082
    error:
        include-stacktrace: never
    servlet:
        context-path: '/ead-course/'

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ead_course?useSSL=false&serverTimezone=UTC
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                use_new_id_generator_mappings: true
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
                jdbc:
                    lob:
                        non-contextual-creation: true
                id:
                    generator:
                        uuid:
                            style: random
